#!/bin/bash

# Script to start and stop netxms services

if [[ $2 == agent ]];then
	if [[ $1 == stop ]]; then
		launchctl unload -w /Library/LaunchDaemons/org.netxms.nxagent.plist 
	else
		launchctl load -w /Library/LaunchDaemons/org.netxms.nxagent.plist
	fi
fi
if [[ $2 == server ]];then
        if [[ $1 == stop ]];then
                launchctl unload -w /Library/LaunchDaemons/org.netxms.server.plist
        else
                launchctl load -w /Library/LaunchDaemons/org.netxms.server.plist
        fi
fi
