#!/bin/bash
#
# Script to monitor printer
#

status="$(/usr/bin/lpq | grep is | awk 'NF>1{print $NF}')"

if [ -z "$status" ]
    then
       	echo "DOWN"
	exit 1
fi
if [ "$status" == "ready" ]
    then
	echo "UP"
	exit 1
fi
echo "DOWN"
